[workspace]
members = ["echo", "app-switcher", "qalc", "code-projects"]
resolver = "2"

[workspace.dependencies]
qpmu-api = { path = "../qpmu/qpmu-api" }

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
