[package]
name = "app-switcher"
version = "0.1.0"
edition = "2021"
metadata.workspace = true

[dependencies]
freedesktop-desktop-entry = "0.7.5"
comette-plugin.workspace = true
tokio = { version = "1.41.1", features = ["fs", "process"] }
