[package]
name = "app-switcher"
version = "0.1.0"
edition = "2021"
metadata.workspace = true

[dependencies]
freedesktop_entry_parser = "1.3.0"
qpmu-api.workspace = true

[lib]
crate-type = ["cdylib"]
