[package]
name = "open"
version = "0.1.0"
edition = "2021"

[dependencies]
qpmu-api.workspace = true
serde = { version = "1.0.214", features = ["derive"] }
toml = { version = "0.8.19", default-features = false, features = ["parse"] }

[lib]
crate-type = ["cdylib"]
