name = "Open"
description = "Open URLs with a query"
repository = "https://github.com/blorbb/qpmu-plugins"
authors = ["blorbb"]

[schema.urls]
title = "List of URLs to show"

[schema.urls.type]
type-name = "map"
value-type.type-name = "struct"
value-type.fields = { name = "str", url = "str" }
