name = "Open"
description = "Open URLs with a query"
repository = "https://github.com/blorbb/covey-plugins"
authors = ["blorbb"]

[schema.urls]
title = "List of URLs to show"
type.map.value-type.struct.fields = { name = "text", url = "text" }
